### ISSUE TITLE
画面のルーティング等の検討

### ISSUE THREAD

**Issue by wkmkymt** [doctor0siki/team-b_4#11]
+ / -> トップページ
+ /search -> 検索
+ /history/ -> 宿泊履歴ページ
+ /villa/[id] -> 別荘詳細
+ /villa/reserve/[id]/ -> 予約ページ

+ /login/ -> ログイン
+ /logout/ -> ログアウト
+ /register/ -> アカウント登録
+ /resign/ -> アカウント削除

**Comment by doctor0siki** [comment]
+ /villa/reserve/confirm/[id]/ -> 予約確認ページ

**Comment by wkmkymt** [comment]
これに合わせましょうか

+ / -> トップページ
+ /search -> 検索
+ /history/ -> 宿泊履歴ページ
+ /villa/[id] -> 別荘詳細
+ /reserve/[id]/ -> 予約ページ
+ /reserve/confirm/[id]/ -> 予約確認ページ

+ /login/ -> ログイン
+ /logout/ -> ログアウト
+ /register/ -> アカウント登録
+ /resign/ -> アカウント削除

**Comment by TenkiGit** [comment]
- /reserve/confirmed ->予約完了
上記を追加します。
